from .models import AnalysisResponse


def build_markdown_report(result: AnalysisResponse) -> str:
    fire_summary = (
        f"{result.fires.count_within_50km} active fire detections within 50 km"
        if result.fires.status == "ok"
        else result.fires.message or "Fire data unavailable"
    )
    aqi_summary = (
        f"AQI {result.air_quality.aqi}, PM2.5 {result.air_quality.pm25} {result.air_quality.unit}"
        if result.air_quality.status == "ok"
        else result.air_quality.message or "Air quality data unavailable"
    )
    weather_summary = (
        f"{result.weather.temperature_c} C, {result.weather.relative_humidity}% humidity, "
        f"{result.weather.wind_speed_kmh} km/h wind"
        if result.weather.status == "ok"
        else result.weather.message or "Weather data unavailable"
    )
    factors = "\n".join(
        f"- {factor.label}: +{factor.points} ({factor.detail})"
        for factor in result.risk.factors
    )
    return f"""# EcoLens Environmental Risk Report

## Location

- Name: {result.location.label}
- Coordinates: {result.location.latitude:.5f}, {result.location.longitude:.5f}

## Current Signals

- Weather: {weather_summary}
- Air Quality: {aqi_summary}
- Active Fires: {fire_summary}

## Risk Assessment

- Level: {result.risk.level}
- Score: {result.risk.score}/100
- Recommendation: {result.risk.recommendation}

## Scoring Factors

{factors}

## Data Sources

- NOAA / National Weather Service API
- OpenAQ API
- NASA FIRMS API

Generated by EcoLens. This report is informational and should not replace official public safety guidance.
"""
